### PR TITLE
Keep private files private

### PR DESCRIPTION
**Pull request by alxy**
Please issue a new version @daftspunk , some more recent changes are not yet pished to the marketplace.

### CODE REVIEW

**Comment by LukeTowers** [comment]
@alxy I'm not sure this makes sense given that this is meant for frontend use and protected files are just protected by checking to see if the backend user is logged in.

**Comment by daftspunk** [comment]
Yes, I agree there is not much point making the file private in most circumstances.

**Comment by daftspunk** [comment]
That's a fair point. Not allowing this code creates an opinion, when we can have it both ways

This can be considered experimental

**Comment by Denoder** [comment]
i feel like this coud be expanded further by allowing only the Frontend User who uploaded it and Backend User to see it. Unless that's already the case?

**Comment by daftspunk** [comment]
I don't think it is and that's the underlying problem. It'll be the front-end user's job now to apply this custom logic, it's too hard for the back-end to manage this requirement. You'd need to implement a custom URL endpoint in the front end to view/download the protected file

**Pull request merged**
